name: flutter_vibrate
description: A Haptic Feedback plugin.
version: 1.3.0
maintainer: Rody Davis (@rodydavis)
homepage: https://github.com/rodydavis/plugins
repository: https://github.com/rodydavis/flutter_vibrate


environment:
  sdk: ^3.5.0
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0


flutter:
  plugin:
    platforms:
      android:
        package: flutter.plugins.vibrate
        pluginClass: VibratePlugin
      ios:
        pluginClass: VibratePlugin
